### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by soonwonh** [grip-unina/TruFor#2]
To get notification when code is available

**Comment by fabrizioguillaro** [comment]
Test code and pre-trained weights are now available

**Comment by StevenGrosz** [comment]
Do you have any plans to release training code?

> Test code and pre-trained weights are now available

**Comment by fabrizioguillaro** [comment]
Yes, but we don't have a release date for it yet

**Comment by qiyuebobo** [comment]
I truly appreciate the work you've done, and  understand if you're not ready to release it yet, but I was wondering if there's any chance you could share the code soon. I believe it could greatly benefit the community, and your contribution would be highly valued.
