### ISSUE TITLE
Question about datasets

### ISSUE THREAD

**Issue by CIawevy** [grip-unina/TruFor#6]
Hi, your work is really fascinating to me .Can you offer me some help about the access to the datasets of  DSO-1, VIPP and CocoGlide. Thanks a lot !

**Comment by CIawevy** [comment]
Also ,the fantastic reality dataset is really hard to fetch, really need help!

**Comment by CIawevy** [comment]
Thanks for your response! I appreciate it. Could you please share the URL for the website you have mentioned? Also, I'd be really grateful if you could notify me once the issues are fixed. Thanks again!

**Comment by OMGGGGG** [comment]
Hi, your work is very interesting. However, I've attempted to contact the authors of the VIPP and FantasticReality multiple times but didn't get any response. It seems that they are no longer maintaining the two datasets, which may make it difficult to continue following your protocol in the future.

**Comment by fabrizioguillaro** [comment]
The link should work, it is reported in the main readme, I'll put it here too: https://www.grip.unina.it/download/prog/TruFor/TruFor_weights.zip

**Comment by CIawevy** [comment]
> The link should work, it is reported in the main readme, I'll put it here too: https://www.grip.unina.it/download/prog/TruFor/TruFor_weights.zip

Hi, I am wondering is  the CocoGlide dataset available now ?

**Comment by CIawevy** [comment]
Many thanks！
